version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - $HOME/.aws:/root/.aws
    working_dir: /app
    ports:
      - "3000:80"
    command: ["sh", "-c", "python main.py"]
